angular.module('myApplication.templates', []).run(['$templateCache', function($templateCache) {
  $templateCache.put("scripts/modules/about/views/about.view.html",
    "<section data-ng-controller=AboutController><div class=\"inner cover\"><h1 class=hidden-xs>{{aboutModel.pagetitle}}</h1><div><p>Singer Adam Czeisler, guitarist Rich Credo, bassist Cole Peterson and drummer Chris Friel write songs, cut records, make videos and play shows to bring the rock to the people.</p><p class=hidden-xs>Albums include Superfriends, Suicide, Ter, Clear The Tarmac, Dance Floor Kills and Parc Boys.</p><br><a href=http://en.wikipedia.org/wiki/Sweet_Water_(band) target=_blank class=\"btn btn-default btn-sm btn-trans\">read more <span class=\"glyphicon glyphicon-chevron-right\"></span></a></div><div class=row>&nbsp;</div><div data-ng-include data-src=\"'scripts/common/partials/social.html'\"></div></div></section>");
  $templateCache.put("scripts/modules/core/views/footer.view.html",
    "<footer><div class=mastfoot><div class=inner><p><a href=\"mailto:info@sweetwaterrocks.com?subject=hello credo\">contact sweet water</a></p></div></div></footer>");
  $templateCache.put("scripts/modules/core/views/header.view.html",
    "<div data-ng-controller=HeaderController><div class=\"masthead clearfix\"><div class=inner><h3 class=masthead-brand><a ui-sref=home>sweet water</a></h3><ul class=\"nav masthead-nav\"><li ui-sref-active=active><a ui-sref=home>Home</a></li><li ui-sref-active=active><a ui-sref=about>About</a></li><li ui-sref-active=active><a ui-sref=news>Subscribe</a></li></ul></div></div></div>");
  $templateCache.put("scripts/modules/core/views/home.view.html",
    "<section data-ng-controller=HomeController id=home><div class=\"inner cover\"><h1 class=hidden-xs>sweet water</h1><p>Sweet Water is the Seattle band whose music combines elements of punk, pop, grunge and new wave to deliver on the promises of rock and roll.</p><div class=row>&nbsp;</div><a href=https://itunes.apple.com/us/album/superstar-live-in-seattle/id941976846 target=_blank class=\"btn btn-lg btn-warning\">Buy Superstar Live</a><div class=row>&nbsp;</div><div data-ng-include data-src=\"'scripts/common/partials/social.html'\"></div></div></section>");
  $templateCache.put("scripts/modules/news/views/news.view.html",
    "<section data-ng-controller=NewsController><div class=\"inner cover\"><h1 class=hidden-xs>{{newsModel.pagetitle}}</h1><div id=mc_embed_signup><form role=form action=\"//sweetwaterrocks.us9.list-manage.com/subscribe/post?u=7b66bffb65e9026ee6bbbf57b&amp;id=758db5b284\" method=post id=mc-embedded-subscribe-form name=mc-embedded-subscribe-form class=validate target=_blank validate><div id=mc_embed_signup_scroll class=\"form-group center-block\" style=max-width:300px><p>Get the 411 on all the latest Sweet h20 stuff.</p><input type=email class=\"form-control email text-center\" name=EMAIL id=mce-EMAIL placeholder=\"email address\" required><div style=\"position: absolute; left: -5000px\"><input name=b_7b66bffb65e9026ee6bbbf57b_758db5b284 tabindex=-1></div></div><button type=submit value=Subscribe name=subscribe id=mc-embedded-subscribe class=\"btn btn-primary\">Submit</button></form></div><div class=row>&nbsp;</div><div data-ng-include data-src=\"'scripts/common/partials/social.html'\"></div></div></section>");
  $templateCache.put("scripts/modules/core/tpl/show.html",
    "<div class=modal-header><button type=button ng-click=cancel() class=close data-dismiss=modal><span aria-hidden=true>&times;</span><span class=sr-only>Close</span></button><h4 class=modal-title>Superstar Live in Seattle out now</h4></div><div class=modal-body><a href=https://itunes.apple.com/us/album/superstar-live-in-seattle/id941976846><img src=images_static/sweet-water-superstar-live-art-200.jpg class=\"center-block img-responsive\"></a><div class=row>&nbsp;</div><a href=https://itunes.apple.com/us/album/superstar-live-in-seattle/id941976846 class=\"btn btn-primary\" ng-click=cancel()>buy now</a></div><div class=row>&nbsp;</div>");
  $templateCache.put("scripts/modules/core/tpl/usermsg.html",
    "<div class=modal-header><h3>{{userMsgHeader}}</h3></div><div class=modal-body><label>{{userMsgBody}}</label></div><div class=modal-footer><button class=\"btn btn-warning\" ng-click=cancel()>OK</button></div>");
  $templateCache.put("scripts/modules/core/tpl/videoOverlay.html",
    "<div class=\"embed-responsive embed-responsive-16by9\"><iframe class=embed-responsive-item src=\"//www.youtube.com/embed/zpOULjyy-n8?rel=0\" allowfullscreen></iframe></div>");
}]);
